name: Build Single Extension

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        repository: julptk/extensions-source
        path: source

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Gradle
      run: cd source/src/id/bacakomik && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: bacakomik-debug-apk
        path: source/src/id/bacakomik/build/outputs/apk/debug/*.apk
